-- Drop table if it already exists to ensure a clean creation
DROP TABLE IF EXISTS public.products;

-- Create the products table
CREATE TABLE public.products (
    id text PRIMARY KEY,
    name text NOT NULL,
    category text NOT NULL,
    image text,
    rate text NOT NULL,
    unit text NOT NULL,
    "transhipmentRates" jsonb NOT NULL,
    "regionWiseRates" jsonb NOT NULL,
    policies text[] NOT NULL
);

-- Enable Row Level Security (RLS) - good practice for security
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

-- Create a policy to allow anonymous users to read products
-- This is important for your public-facing product portal
CREATE POLICY "Enable read access for all users" ON public.products
FOR SELECT USING (true);

-- Insert initial product data
INSERT INTO public.products (id, name, category, image, rate, unit, "transhipmentRates", "regionWiseRates", policies) VALUES
('prod-urea-tara', 'Tara Urea', 'UREA', '/placeholder.svg?height=200&width=200', 'Rs. 2,850', 'per bag (50kg)', '[{"region": "Punjab", "rate": "Rs. 2,800"}, {"region": "Sindh", "rate": "Rs. 2,820"}, {"region": "KPK", "rate": "Rs. 2,830"}, {"region": "Balochistan", "rate": "Rs. 2,850"}]', '[{"region": "Lahore", "rate": "Rs. 2,850"}, {"region": "Karachi", "rate": "Rs. 2,870"}, {"region": "Islamabad", "rate": "Rs. 2,860"}, {"region": "Faisalabad", "rate": "Rs. 2,840"}]', '{"Minimum order: 10 bags", "Payment terms: 30 days credit for registered dealers", "Transportation included within 50km radius", "Quality guarantee: 46% Nitrogen content minimum"}'),
('prod-urea-bs', 'B-S Urea (FAT)', 'UREA', '/placeholder.svg?height=200&width=200', 'Rs. 2,900', 'per bag (50kg)', '[{"region": "Punjab", "rate": "Rs. 2,850"}, {"region": "Sindh", "rate": "Rs. 2,870"}, {"region": "KPK", "rate": "Rs. 2,880"}, {"region": "Balochistan", "rate": "Rs. 2,900"}]', '[{"region": "Lahore", "rate": "Rs. 2,900"}, {"region": "Karachi", "rate": "Rs. 2,920"}, {"region": "Islamabad", "rate": "Rs. 2,910"}, {"region": "Faisalabad", "rate": "Rs. 2,890"}]', '{"Premium quality with enhanced formula", "Minimum order: 5 bags", "Free soil testing with bulk orders (100+ bags)", "Seasonal discounts available"}'),
('prod-urea-engro', 'Engro Urea', 'UREA', '/placeholder.svg?height=200&width=200', 'Rs. 2,920', 'per bag (50kg)', '[{"region": "Punjab", "rate": "Rs. 2,870"}, {"region": "Sindh", "rate": "Rs. 2,890"}, {"region": "KPK", "rate": "Rs. 2,900"}, {"region": "Balochistan", "rate": "Rs. 2,920"}]', '[{"region": "Lahore", "rate": "Rs. 2,920"}, {"region": "Karachi", "rate": "Rs. 2,940"}, {"region": "Islamabad", "rate": "Rs. 2,930"}, {"region": "Faisalabad", "rate": "Rs. 2,910"}]', '{"Trusted brand with consistent quality", "Available in both granular and prilled form", "Bulk discount: 2% on orders above 200 bags", "Technical support included"}'),
('prod-urea-engro-nfml', 'Engro (NFML) Urea', 'UREA', '/placeholder.svg?height=200&width=200', 'Rs. 2,950', 'per bag (50kg)', '[{"region": "Punjab", "rate": "Rs. 2,900"}, {"region": "Sindh", "rate": "Rs. 2,920"}, {"region": "KPK", "rate": "Rs. 2,930"}, {"region": "Balochistan", "rate": "Rs. 2,950"}]', '[{"region": "Lahore", "rate": "Rs. 2,950"}, {"region": "Karachi", "rate": "Rs. 2,970"}, {"region": "Islamabad", "rate": "Rs. 2,960"}, {"region": "Faisalabad", "rate": "Rs. 2,940"}]', '{"NFML certified quality", "Extended shelf life", "Suitable for all crop types", "Weather-resistant packaging"}'),
('prod-urea-fatima-nfml', 'Fatima (NFML) (FAT) Urea', 'UREA', '/placeholder.svg?height=200&width=200', 'Rs. 2,980', 'per bag (50kg)', '[{"region": "Punjab", "rate": "Rs. 2,930"}, {"region": "Sindh", "rate": "Rs. 2,950"}, {"region": "KPK", "rate": "Rs. 2,960"}, {"region": "Balochistan", "rate": "Rs. 2,980"}]', '[{"region": "Lahore", "rate": "Rs. 2,980"}, {"region": "Karachi", "rate": "Rs. 3,000"}, {"region": "Islamabad", "rate": "Rs. 2,990"}, {"region": "Faisalabad", "rate": "Rs. 2,970"}]', '{"Premium NFML grade", "Enhanced with micronutrients", "Recommended for high-value crops", "Certificate of analysis provided"}'),
('prod-urea-fatima', 'Fatima (FAT) Urea', 'UREA', '/placeholder.svg?height=200&width=200', 'Rs. 2,960', 'per bag (50kg)', '[{"region": "Punjab", "rate": "Rs. 2,910"}, {"region": "Sindh", "rate": "Rs. 2,930"}, {"region": "KPK", "rate": "Rs. 2,940"}, {"region": "Balochistan", "rate": "Rs. 2,960"}]', '[{"region": "Lahore", "rate": "Rs. 2,960"}, {"region": "Karachi", "rate": "Rs. 2,980"}, {"region": "Islamabad", "rate": "Rs. 2,970"}, {"region": "Faisalabad", "rate": "Rs. 2,950"}]', '{"Standard FAT grade", "Consistent granule size", "Good for broadcast application", "Moisture-resistant packaging"}'),
('prod-urea-imp', 'IMP. Urea', 'UREA', '/placeholder.svg?height=200&width=200', 'Rs. 3,100', 'per bag (50kg)', '[{"region": "Punjab", "rate": "Rs. 3,050"}, {"region": "Sindh", "rate": "Rs. 3,070"}, {"region": "KPK", "rate": "Rs. 3,080"}, {"region": "Balochistan", "rate": "Rs. 3,100"}]', '[{"region": "Lahore", "rate": "Rs. 3,100"}, {"region": "Karachi", "rate": "Rs. 3,120"}, {"region": "Islamabad", "rate": "Rs. 3,110"}, {"region": "Faisalabad", "rate": "Rs. 3,090"}]', '{"Imported premium quality", "Higher nitrogen content", "Limited stock availability", "Advance booking required"}'),
('prod-urea-sona-g', 'Sona Urea-G', 'UREA', '/placeholder.svg?height=200&width=200', 'Rs. 2,890', 'per bag (50kg)', '[{"region": "Punjab", "rate": "Rs. 2,840"}, {"region": "Sindh", "rate": "Rs. 2,860"}, {"region": "KPK", "rate": "Rs. 2,870"}, {"region": "Balochistan", "rate": "Rs. 2,890"}]', '[{"region": "Lahore", "rate": "Rs. 2,890"}, {"region": "Karachi", "rate": "Rs. 2,910"}, {"region": "Islamabad", "rate": "Rs. 2,900"}, {"region": "Faisalabad", "rate": "Rs. 2,880"}]', '{"Granular form for easy application", "Suitable for all soil types", "Cost-effective option", "Regular supply guaranteed"}'),
('prod-urea-sona-neem', 'Sona Urea Neem Coated', 'UREA', '/placeholder.svg?height=200&width=200', 'Rs. 3,050', 'per bag (50kg)', '[{"region": "Punjab", "rate": "Rs. 3,000"}, {"region": "Sindh", "rate": "Rs. 3,020"}, {"region": "KPK", "rate": "Rs. 3,030"}, {"region": "Balochistan", "rate": "Rs. 3,050"}]', '[{"region": "Lahore", "rate": "Rs. 3,050"}, {"region": "Karachi", "rate": "Rs. 3,070"}, {"region": "Islamabad", "rate": "Rs. 3,060"}, {"region": "Faisalabad", "rate": "Rs. 3,040"}]', '{"Neem coated for slow release", "Reduces nitrogen loss", "Eco-friendly option", "Higher efficiency per application"}'),
('prod-urea-sona-p', 'Sona Urea-P', 'UREA', '/placeholder.svg?height=200&width=200', 'Rs. 2,870', 'per bag (50kg)', '[{"region": "Punjab", "rate": "Rs. 2,820"}, {"region": "Sindh", "rate": "Rs. 2,840"}, {"region": "KPK", "rate": "Rs. 2,850"}, {"region": "Balochistan", "rate": "Rs. 2,870"}]', '[{"region": "Lahore", "rate": "Rs. 2,870"}, {"region": "Karachi", "rate": "Rs. 2,890"}, {"region": "Islamabad", "rate": "Rs. 2,880"}, {"region": "Faisalabad", "rate": "Rs. 2,860"}]', '{"Prilled form for quick dissolution", "Ideal for fertigation systems", "Fast-acting formula", "Uniform nutrient distribution"}'),
('prod-urea-sona-p-nfml', 'Sona-P (NFML) Urea', 'UREA', '/placeholder.svg?height=200&width=200', 'Rs. 2,940', 'per bag (50kg)', '[{"region": "Punjab", "rate": "Rs. 2,890"}, {"region": "Sindh", "rate": "Rs. 2,910"}, {"region": "KPK", "rate": "Rs. 2,920"}, {"region": "Balochistan", "rate": "Rs. 2,940"}]', '[{"region": "Lahore", "rate": "Rs. 2,940"}, {"region": "Karachi", "rate": "Rs. 2,960"}, {"region": "Islamabad", "rate": "Rs. 2,950"}, {"region": "Faisalabad", "rate": "Rs. 2,930"}]', '{"NFML certified prilled urea", "Superior quality standards", "Consistent performance", "Laboratory tested"}'),
('prod-urea-tara-nfml', 'Tara (NFML) Urea', 'UREA', '/placeholder.svg?height=200&width=200', 'Rs. 2,930', 'per bag (50kg)', '[{"region": "Punjab", "rate": "Rs. 2,880"}, {"region": "Sindh", "rate": "Rs. 2,900"}, {"region": "KPK", "rate": "Rs. 2,910"}, {"region": "Balochistan", "rate": "Rs. 2,930"}]', '[{"region": "Lahore", "rate": "Rs. 2,930"}, {"region": "Karachi", "rate": "Rs. 2,950"}, {"region": "Islamabad", "rate": "Rs. 2,940"}, {"region": "Faisalabad", "rate": "Rs. 2,920"}]', '{"NFML grade Tara brand", "Reliable supply chain", "Competitive pricing", "Dealer support program"}'),
('prod-urea-zinc-coated', 'Urea Zinc Coated', 'UREA', '/placeholder.svg?height=200&width=200', 'Rs. 3,150', 'per bag (50kg)', '[{"region": "Punjab", "rate": "Rs. 3,100"}, {"region": "Sindh", "rate": "Rs. 3,120"}, {"region": "KPK", "rate": "Rs. 3,130"}, {"region": "Balochistan", "rate": "Rs. 3,150"}]', '[{"region": "Lahore", "rate": "Rs. 3,150"}, {"region": "Karachi", "rate": "Rs. 3,170"}, {"region": "Islamabad", "rate": "Rs. 3,160"}, {"region": "Faisalabad", "rate": "Rs. 3,140"}]', '{"Zinc coated for micronutrient delivery", "Enhances crop health and yield", "Reduces zinc deficiency in soil", "Specialty product, limited stock"}'),
('prod-urea-zabardast', 'Urea Zabardast', 'UREA', '/placeholder.svg?height=200&width=200', 'Rs. 3,000', 'per bag (50kg)', '[{"region": "Punjab", "rate": "Rs. 2,950"}, {"region": "Sindh", "rate": "Rs. 2,970"}, {"region": "KPK", "rate": "Rs. 2,980"}, {"region": "Balochistan", "rate": "Rs. 3,000"}]', '[{"region": "Lahore", "rate": "Rs. 3,000"}, {"region": "Karachi", "rate": "Rs. 3,020"}, {"region": "Islamabad", "rate": "Rs. 3,010"}, {"region": "Faisalabad", "rate": "Rs. 2,990"}]', '{"High-performance urea", "Designed for maximum nutrient uptake", "Suitable for all major crops", "Premium quality, consistent results"}'),
('prod-dap-fatima', 'G Fatima (FAT) DAP', 'DAP', '/placeholder.svg?height=200&width=200', 'Rs. 3,450', 'per bag (50kg)', '[{"region": "Punjab", "rate": "Rs. 3,400"}, {"region": "Sindh", "rate": "Rs. 3,420"}, {"region": "KPK", "rate": "Rs. 3,430"}, {"region": "Balochistan", "rate": "Rs. 3,450"}]', '[{"region": "Lahore", "rate": "Rs. 3,450"}, {"region": "Karachi", "rate": "Rs. 3,470"}, {"region": "Islamabad", "rate": "Rs. 3,460"}, {"region": "Faisalabad", "rate": "Rs. 3,440"}]', '{"High phosphorus content (18% P2O5)", "Suitable for all crops", "Best for soil application", "Bulk orders get 1.5% discount"}'),
('prod-dap-barket-sv', 'Barket-SV DAP', 'DAP', '/placeholder.svg?height=200&width=200', 'Rs. 3,380', 'per bag (50kg)', '[{"region": "Punjab", "rate": "Rs. 3,330"}, {"region": "Sindh", "rate": "Rs. 3,350"}, {"region": "KPK", "rate": "Rs. 3,360"}, {"region": "Balochistan", "rate": "Rs. 3,380"}]', '[{"region": "Lahore", "rate": "Rs. 3,380"}, {"region": "Karachi", "rate": "Rs. 3,400"}, {"region": "Islamabad", "rate": "Rs. 3,390"}, {"region": "Faisalabad", "rate": "Rs. 3,370"}]', '{"Standard DAP formulation", "Good for cereal crops", "Available year-round", "Quality assurance certificate"}'),
('prod-dap-engro', 'Engro DAP', 'DAP', '/placeholder.svg?height=200&width=200', 'Rs. 3,420', 'per bag (50kg)', '[{"region": "Punjab", "rate": "Rs. 3,370"}, {"region": "Sindh", "rate": "Rs. 3,390"}, {"region": "KPK", "rate": "Rs. 3,400"}, {"region": "Balochistan", "rate": "Rs. 3,420"}]', '[{"region": "Lahore", "rate": "Rs. 3,420"}, {"region": "Karachi", "rate": "Rs. 3,440"}, {"region": "Islamabad", "rate": "Rs. 3,430"}, {"region": "Faisalabad", "rate": "Rs. 3,410"}]', '{"Premium Engro quality", "Enhanced with micronutrients", "Technical advisory support", "Proven crop performance"}'),
('prod-dap-ffbl', 'FFBL DAP', 'DAP', '/placeholder.svg?height=200&width=200', 'Rs. 3,400', 'per bag (50kg)', '[{"region": "Punjab", "rate": "Rs. 3,350"}, {"region": "Sindh", "rate": "Rs. 3,370"}, {"region": "KPK", "rate": "Rs. 3,380"}, {"region": "Balochistan", "rate": "Rs. 3,400"}]', '[{"region": "Lahore", "rate": "Rs. 3,400"}, {"region": "Karachi", "rate": "Rs. 3,420"}, {"region": "Islamabad", "rate": "Rs. 3,410"}, {"region": "Faisalabad", "rate": "Rs. 3,390"}]', '{"FFBL trusted brand", "Consistent quality", "Good solubility", "Farmer-friendly pricing"}'),
('prod-dap-ffc', 'FFC DAP', 'DAP', '/placeholder.svg?height=200&width=200', 'Rs. 3,390', 'per bag (50kg)', '[{"region": "Punjab", "rate": "Rs. 3,340"}, {"region": "Sindh", "rate": "Rs. 3,360"}, {"region": "KPK", "rate": "Rs. 3,370"}, {"region": "Balochistan", "rate": "Rs. 3,390"}]', '[{"region": "Lahore", "rate": "Rs. 3,390"}, {"region": "Karachi", "rate": "Rs. 3,410"}, {"region": "Islamabad", "rate": "Rs. 3,400"}, {"region": "Faisalabad", "rate": "Rs. 3,380"}]', '{"FFC premium quality", "High nutrient efficiency", "Suitable for all soil types", "Long-term soil health benefits"}'),
('prod-dap-sarsabz', 'Sarsabz (FAT) DAP', 'DAP', '/placeholder.svg?height=200&width=200', 'Rs. 3,460', 'per bag (50kg)', '[{"region": "Punjab", "rate": "Rs. 3,410"}, {"region": "Sindh", "rate": "Rs. 3,430"}, {"region": "KPK", "rate": "Rs. 3,440"}, {"region": "Balochistan", "rate": "Rs. 3,460"}]', '[{"region": "Lahore", "rate": "Rs. 3,460"}, {"region": "Karachi", "rate": "Rs. 3,480"}, {"region": "Islamabad", "rate": "Rs. 3,470"}, {"region": "Faisalabad", "rate": "Rs. 3,450"}]', '{"Premium Sarsabz quality", "Enhanced formulation", "Better crop yields", "Technical support included"}'),
('prod-dap-sona', 'Sona DAP', 'DAP', '/placeholder.svg?height=200&width=200', 'Rs. 3,370', 'per bag (50kg)', '[{"region": "Punjab", "rate": "Rs. 3,320"}, {"region": "Sindh", "rate": "Rs. 3,340"}, {"region": "KPK", "rate": "Rs. 3,350"}, {"region": "Balochistan", "rate": "Rs. 3,370"}]', '[{"region": "Lahore", "rate": "Rs. 3,370"}, {"region": "Karachi", "rate": "Rs. 3,390"}, {"region": "Islamabad", "rate": "Rs. 3,380"}, {"region": "Faisalabad", "rate": "Rs. 3,360"}]', '{"Cost-effective DAP option", "Standard nutrient content", "Regular availability", "Suitable for small farmers"}'),
('prod-dap-7star', 'DAP-7Star', 'DAP', '/placeholder.svg?height=200&width=200', 'Rs. 3,410', 'per bag (50kg)', '[{"region": "Punjab", "rate": "Rs. 3,360"}, {"region": "Sindh", "rate": "Rs. 3,380"}, {"region": "KPK", "rate": "Rs. 3,390"}, {"region": "Balochistan", "rate": "Rs. 3,410"}]', '[{"region": "Lahore", "rate": "Rs. 3,410"}, {"region": "Karachi", "rate": "Rs. 3,430"}, {"region": "Islamabad", "rate": "Rs. 3,420"}, {"region": "Faisalabad", "rate": "Rs. 3,400"}]', '{"7Star premium DAP", "High purity", "Fast acting", "Excellent for initial growth"}'),
('prod-dap-ss', 'Dap-SS', 'DAP', '/placeholder.svg?height=200&width=200', 'Rs. 3,350', 'per bag (50kg)', '[{"region": "Punjab", "rate": "Rs. 3,300"}, {"region": "Sindh", "rate": "Rs. 3,320"}, {"region": "KPK", "rate": "Rs. 3,330"}, {"region": "Balochistan", "rate": "Rs. 3,350"}]', '[{"region": "Lahore", "rate": "Rs. 3,350"}, {"region": "Karachi", "rate": "Rs. 3,370"}, {"region": "Islamabad", "rate": "Rs. 3,360"}, {"region": "Faisalabad", "rate": "Rs. 3,340"}]', '{"Standard SS grade DAP", "Reliable performance", "Cost-effective", "Widely available"}'),
('prod-dap-superstar', 'DAP-Super Star', 'DAP', '/placeholder.svg?height=200&width=200', 'Rs. 3,480', 'per bag (50kg)', '[{"region": "Punjab", "rate": "Rs. 3,430"}, {"region": "Sindh", "rate": "Rs. 3,450"}, {"region": "KPK", "rate": "Rs. 3,460"}, {"region": "Balochistan", "rate": "Rs. 3,480"}]', '[{"region": "Lahore", "rate": "Rs. 3,480"}, {"region": "Karachi", "rate": "Rs. 3,500"}, {"region": "Islamabad", "rate": "Rs. 3,490"}, {"region": "Faisalabad", "rate": "Rs. 3,470"}]', '{"Super Star premium DAP", "Enhanced nutrient uptake", "Maximized yield potential", "Exclusive product"}'),
('prod-dap-vah-aus', 'DAP-Vah (Aus)', 'DAP', '/placeholder.svg?height=200&width=200', 'Rs. 3,500', 'per bag (50kg)', '[{"region": "Punjab", "rate": "Rs. 3,450"}, {"region": "Sindh", "rate": "Rs. 3,470"}, {"region": "KPK", "rate": "Rs. 3,480"}, {"region": "Balochistan", "rate": "Rs. 3,500"}]', '[{"region": "Lahore", "rate": "Rs. 3,500"}, {"region": "Karachi", "rate": "Rs. 3,520"}, {"region": "Islamabad", "rate": "Rs. 3,510"}, {"region": "Faisalabad", "rate": "Rs. 3,490"}]', '{"Imported Australian DAP", "Superior quality and purity", "Highly soluble", "Recommended for high-value crops"}'),
('prod-can-f', 'CAN-F (Pakarab)', 'CAN', '/placeholder.svg?height=200&width=200', 'Rs. 1,950', 'per bag (50kg)', '[{"region": "Punjab", "rate": "Rs. 1,900"}, {"region": "Sindh", "rate": "Rs. 1,920"}, {"region": "KPK", "rate": "Rs. 1,930"}, {"region": "Balochistan", "rate": "Rs. 1,950"}]', '[{"region": "Lahore", "rate": "Rs. 1,950"}, {"region": "Karachi", "rate": "Rs. 1,970"}, {"region": "Islamabad", "rate": "Rs. 1,960"}, {"region": "Faisalabad", "rate": "Rs. 1,940"}]', '{"Pakarab CAN-F grade", "26% Nitrogen content", "Quick-acting formula", "Ideal for top dressing"}'),
('prod-can-g', 'CAN-G (FAT)', 'CAN', '/placeholder.svg?height=200&width=200', 'Rs. 1,980', 'per bag (50kg)', '[{"region": "Punjab", "rate": "Rs. 1,930"}, {"region": "Sindh", "rate": "Rs. 1,950"}, {"region": "KPK", "rate": "Rs. 1,960"}, {"region": "Balochistan", "rate": "Rs. 1,980"}]', '[{"region": "Lahore", "rate": "Rs. 1,980"}, {"region": "Karachi", "rate": "Rs. 2,000"}, {"region": "Islamabad", "rate": "Rs. 1,990"}, {"region": "Faisalabad", "rate": "Rs. 1,970"}]', '{"FAT grade CAN", "Enhanced granule strength", "Better storage stability", "Premium quality assurance"}'),
('prod-as', 'A-S', 'A-S', '/placeholder.svg?height=200&width=200', 'Rs. 1,850', 'per bag (50kg)', '[{"region": "Punjab", "rate": "Rs. 1,800"}, {"region": "Sindh", "rate": "Rs. 1,820"}, {"region": "KPK", "rate": "Rs. 1,830"}, {"region": "Balochistan", "rate": "Rs. 1,850"}]', '[{"region": "Lahore", "rate": "Rs. 1,850"}, {"region": "Karachi", "rate": "Rs. 1,870"}, {"region": "Islamabad", "rate": "Rs. 1,860"}, {"region": "Faisalabad", "rate": "Rs. 1,840"}]', '{"Specialty A-S formulation", "Unique nutrient blend", "Suitable for specific crops", "Limited availability"}'),
('prod-mop', 'MOP', 'MOP', '/placeholder.svg?height=200&width=200', 'Rs. 2,100', 'per bag (50kg)', '[{"region": "Punjab", "rate": "Rs. 2,050"}, {"region": "Sindh", "rate": "Rs. 2,070"}, {"region": "KPK", "rate": "Rs. 2,080"}, {"region": "Balochistan", "rate": "Rs. 2,100"}]', '[{"region": "Lahore", "rate": "Rs. 2,100"}, {"region": "Karachi", "rate": "Rs. 2,120"}, {"region": "Islamabad", "rate": "Rs. 2,110"}, {"region": "Faisalabad", "rate": "Rs. 2,090"}]', '{"Standard MOP grade", "60% K2O content", "Suitable for all crops", "Good storage stability"}'),
('prod-mop-barkat-pink', 'Barkat Pink-G MOP', 'MOP', '/placeholder.svg?height=200&width=200', 'Rs. 2,180', 'per bag (50kg)', '[{"region": "Punjab", "rate": "Rs. 2,130"}, {"region": "Sindh", "rate": "Rs. 2,150"}, {"region": "KPK", "rate": "Rs. 2,160"}, {"region": "Balochistan", "rate": "Rs. 2,180"}]', '[{"region": "Lahore", "rate": "Rs. 2,180"}, {"region": "Karachi", "rate": "Rs. 2,200"}, {"region": "Islamabad", "rate": "Rs. 2,190"}, {"region": "Faisalabad", "rate": "Rs. 2,170"}]', '{"Premium pink granular MOP", "Enhanced solubility", "Better crop response", "Barkat quality assurance"}'),
('prod-mop-barkat-white', 'Mop Barkat White', 'MOP', '/placeholder.svg?height=200&width=200', 'Rs. 2,200', 'per bag (50kg)', '[{"region": "Punjab", "rate": "Rs. 2,150"}, {"region": "Sindh", "rate": "Rs. 2,170"}, {"region": "KPK", "rate": "Rs. 2,180"}, {"region": "Balochistan", "rate": "Rs. 2,200"}]', '[{"region": "Lahore", "rate": "Rs. 2,200"}, {"region": "Karachi", "rate": "Rs. 2,220"}, {"region": "Islamabad", "rate": "Rs. 2,210"}, {"region": "Faisalabad", "rate": "Rs. 2,190"}]', '{"White granular MOP", "Balanced N-P formulation", "Good for starter application", "Premium Barkat quality"}'),
('prod-mop-ffc', 'MOP FFC', 'MOP', '/placeholder.svg?height=200&width=200', 'Rs. 2,190', 'per bag (50kg)', '[{"region": "Punjab", "rate": "Rs. 2,140"}, {"region": "Sindh", "rate": "Rs. 2,160"}, {"region": "KPK", "rate": "Rs. 2,170"}, {"region": "Balochistan", "rate": "Rs. 2,190"}]', '[{"region": "Lahore", "rate": "Rs. 2,190"}, {"region": "Karachi", "rate": "Rs. 2,210"}, {"region": "Islamabad", "rate": "Rs. 2,200"}, {"region": "Faisalabad", "rate": "Rs. 2,180"}]', '{"FFC MOP grade", "High potassium content", "Suitable for all crops", "Reliable supply"}'),
('prod-np-engro-plus', 'Engro Plus 18:18 NP', 'NP', '/placeholder.svg?height=200&width=200', 'Rs. 2,850', 'per bag (50kg)', '[{"region": "Punjab", "rate": "Rs. 2,800"}, {"region": "Sindh", "rate": "Rs. 2,820"}, {"region": "KPK", "rate": "Rs. 2,830"}, {"region": "Balochistan", "rate": "Rs. 2,850"}]', '[{"region": "Lahore", "rate": "Rs. 2,850"}, {"region": "Karachi", "rate": "Rs. 2,870"}, {"region": "Islamabad", "rate": "Rs. 2,860"}, {"region": "Faisalabad", "rate": "Rs. 2,840"}]', '{"Balanced 18:18 NP formula", "Engro premium quality", "Suitable for all crops", "Enhanced with micronutrients"}'),
('prod-np-ss', 'Np-SS', 'NP', '/placeholder.svg?height=200&width=200', 'Rs. 2,820', 'per bag (50kg)', '[{"region": "Punjab", "rate": "Rs. 2,770"}, {"region": "Sindh", "rate": "Rs. 2,790"}, {"region": "KPK", "rate": "Rs. 2,800"}, {"region": "Balochistan", "rate": "Rs. 2,820"}]', '[{"region": "Lahore", "rate": "Rs. 2,820"}, {"region": "Karachi", "rate": "Rs. 2,840"}, {"region": "Islamabad", "rate": "Rs. 2,830"}, {"region": "Faisalabad", "rate": "Rs. 2,810"}]', '{"Standard SS grade NP", "Cost-effective", "Good for general crop use", "Consistent supply"}'),
('prod-sop-seed-askari', 'SOP Seed Askari', 'SOP-G', '/placeholder.svg?height=200&width=200', 'Rs. 4,250', 'per bag (50kg)', '[{"region": "Punjab", "rate": "Rs. 4,200"}, {"region": "Sindh", "rate": "Rs. 4,220"}, {"region": "KPK", "rate": "Rs. 4,230"}, {"region": "Balochistan", "rate": "Rs. 4,250"}]', '[{"region": "Lahore", "rate": "Rs. 4,250"}, {"region": "Karachi", "rate": "Rs. 4,270"}, {"region": "Islamabad", "rate": "Rs. 4,260"}, {"region": "Faisalabad", "rate": "Rs. 4,240"}]', '{"SOP specifically for seed treatment", "Enhances germination and early growth", "High purity", "Limited seasonal availability"}'),
('prod-sop-g-barkat', 'SOP-G Barkat', 'SOP-G', '/placeholder.svg?height=200&width=200', 'Rs. 4,150', 'per bag (50kg)', '[{"region": "Punjab", "rate": "Rs. 4,100"}, {"region": "Sindh", "rate": "Rs. 4,120"}, {"region": "KPK", "rate": "Rs. 4,130"}, {"region": "Balochistan", "rate": "Rs. 4,150"}]', '[{"region": "Lahore", "rate": "Rs. 4,150"}, {"region": "Karachi", "rate": "Rs. 4,170"}, {"region": "Islamabad", "rate": "Rs. 4,160"}, {"region": "Faisalabad", "rate": "Rs. 4,140"}]', '{"Barkat SOP granular", "High-quality potassium source", "Good for quality crops", "Trusted brand reliability"}'),
('prod-sop-g-vah', 'SOP-G Vah', 'SOP-G', '/placeholder.svg?height=200&width=200', 'Rs. 4,170', 'per bag (50kg)', '[{"region": "Punjab", "rate": "Rs. 4,120"}, {"region": "Sindh", "rate": "Rs. 4,140"}, {"region": "KPK", "rate": "Rs. 4,150"}, {"region": "Balochistan", "rate": "Rs. 4,170"}]', '[{"region": "Lahore", "rate": "Rs. 4,170"}, {"region": "Karachi", "rate": "Rs. 4,190"}, {"region": "Islamabad", "rate": "Rs. 4,180"}, {"region": "Faisalabad", "rate": "Rs. 4,160"}]', '{"Vah SOP granular", "Enhanced nutrient availability", "Suitable for sensitive crops", "Premium quality grade"}'),
('prod-sop-g-ffc', 'SOP-G FFC', 'SOP-G', '/placeholder.svg?height=200&width=200', 'Rs. 4,180', 'per bag (50kg)', '[{"region": "Punjab", "rate": "Rs. 4,130"}, {"region": "Sindh", "rate": "Rs. 4,150"}, {"region": "KPK", "rate": "Rs. 4,160"}, {"region": "Balochistan", "rate": "Rs. 4,180"}]', '[{"region": "Lahore", "rate": "Rs. 4,180"}, {"region": "Karachi", "rate": "Rs. 4,200"}, {"region": "Islamabad", "rate": "Rs. 4,190"}, {"region": "Faisalabad", "rate": "Rs. 4,170"}]', '{"FFC premium SOP", "Superior granulation", "Enhanced crop quality", "Technical support available"}'),
('prod-sop-p-vah', 'SOP-P Vah', 'SOP-P', '/placeholder.svg?height=200&width=200', 'Rs. 4,190', 'per bag (50kg)', '[{"region": "Punjab", "rate": "Rs. 4,140"}, {"region": "Sindh", "rate": "Rs. 4,160"}, {"region": "KPK", "rate": "Rs. 4,170"}, {"region": "Balochistan", "rate": "Rs. 4,190"}]', '[{"region": "Lahore", "rate": "Rs. 4,190"}, {"region": "Karachi", "rate": "Rs. 4,210"}, {"region": "Islamabad", "rate": "Rs. 4,200"}, {"region": "Faisalabad", "rate": "Rs. 4,180"}]', '{"Vah SOP powder", "Fine particle size for quick dissolution", "Ideal for foliar application", "High purity"}'),
('prod-sop-p-barkat', 'SOP-P Barkat', 'SOP-P', '/placeholder.svg?height=200&width=200', 'Rs. 4,120', 'per bag (50kg)', '[{"region": "Punjab", "rate": "Rs. 4,070"}, {"region": "Sindh", "rate": "Rs. 4,090"}, {"region": "KPK", "rate": "Rs. 4,100"}, {"region": "Balochistan", "rate": "Rs. 4,120"}]', '[{"region": "Lahore", "rate": "Rs. 4,120"}, {"region": "Karachi", "rate": "Rs. 4,140"}, {"region": "Islamabad", "rate": "Rs. 4,130"}, {"region": "Faisalabad", "rate": "Rs. 4,110"}]', '{"Barkat SOP powder", "Fine particle size", "Good for fertigation", "Uniform nutrient distribution"}'),
('prod-sspg', 'SSPG', 'SSPG', '/placeholder.svg?height=200&width=200', 'Rs. 3,200', 'per bag (50kg)', '[{"region": "Punjab", "rate": "Rs. 3,150"}, {"region": "Sindh", "rate": "Rs. 3,170"}, {"region": "KPK", "rate": "Rs. 3,180"}, {"region": "Balochistan", "rate": "Rs. 3,200"}]', '[{"region": "Lahore", "rate": "Rs. 3,200"}, {"region": "Karachi", "rate": "Rs. 3,220"}, {"region": "Islamabad", "rate": "Rs. 3,210"}, {"region": "Faisalabad", "rate": "Rs. 3,190"}]', '{"Single Super Phosphate Granular", "16% P2O5, 12% S", "Good for acidic soils", "Slow-release phosphorus"}'),
('prod-zarkhaiz-plus', 'Zarkhaiz Plus (MOP)', 'ZINC', '/placeholder.svg?height=200&width=200', 'Rs. 2,950', 'per bag (50kg)', '[{"region": "Punjab", "rate": "Rs. 2,900"}, {"region": "Sindh", "rate": "Rs. 2,920"}, {"region": "KPK", "rate": "Rs. 2,930"}, {"region": "Balochistan", "rate": "Rs. 2,950"}]', '[{"region": "Lahore", "rate": "Rs. 2,950"}, {"region": "Karachi", "rate": "Rs. 2,970"}, {"region": "Islamabad", "rate": "Rs. 2,960"}, {"region": "Faisalabad", "rate": "Rs. 2,940"}]', '{"Premium specialty fertilizer", "High-yield formula", "Suitable for cash crops", "Limited seasonal stock"}'),
('prod-sona-zinc', 'Sona Zinc', 'ZINC', '/placeholder.svg?height=200&width=200', 'Rs. 2,800', 'per bag (50kg)', '[{"region": "Punjab", "rate": "Rs. 2,750"}, {"region": "Sindh", "rate": "Rs. 2,770"}, {"region": "KPK", "rate": "Rs. 2,780"}, {"region": "Balochistan", "rate": "Rs. 2,800"}]', '[{"region": "Lahore", "rate": "Rs. 2,800"}, {"region": "Karachi", "rate": "Rs. 2,820"}, {"region": "Islamabad", "rate": "Rs. 2,810"}, {"region": "Faisalabad", "rate": "Rs. 2,790"}]', '{"Sona Zinc fortification", "Micronutrient enriched", "Prevents zinc deficiency", "Suitable for all crops"}'),
('prod-sona-zinc-sulphate', 'Sona Zinc Sulphate G', 'ZINC', '/placeholder.svg?height=200&width=200', 'Rs. 2,900', 'per bag (50kg)', '[{"region": "Punjab", "rate": "Rs. 2,850"}, {"region": "Sindh", "rate": "Rs. 2,870"}, {"region": "KPK", "rate": "Rs. 2,880"}, {"region": "Balochistan", "rate": "Rs. 2,900"}]', '[{"region": "Lahore", "rate": "Rs. 2,900"}, {"region": "Karachi", "rate": "Rs. 2,920"}, {"region": "Islamabad", "rate": "Rs. 2,910"}, {"region": "Faisalabad", "rate": "Rs. 2,890"}]', '{"Granular Zinc Sulphate", "High zinc content for rapid absorption", "Corrects zinc deficiencies quickly", "Recommended for rice and maize"}'),
('prod-boron-borex', 'Boron Borex', 'BORON', '/placeholder.svg?height=200&width=200', 'Rs. 1,500', 'per kg', '[{"region": "Punjab", "rate": "Rs. 1,450"}, {"region": "Sindh", "rate": "Rs. 1,470"}, {"region": "KPK", "rate": "Rs. 1,480"}, {"region": "Balochistan", "rate": "Rs. 1,500"}]', '[{"region": "Lahore", "rate": "Rs. 1,500"}, {"region": "Karachi", "rate": "Rs. 1,520"}, {"region": "Islamabad", "rate": "Rs. 1,510"}, {"region": "Faisalabad", "rate": "Rs. 1,490"}]', '{"High-grade Boron fertilizer", "Essential for flowering and fruit setting", "Water-soluble powder", "Apply as per soil test recommendations"}');

-- Policy to allow authenticated users to insert, update, and delete products
CREATE POLICY "Enable write access for authenticated users" ON public.products
FOR ALL TO authenticated USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);
